

## TMDB API : https://developers.themoviedb.org/
## RapidAPI : https://rapidapi.com/collection/list-of-free-apis
JSON Viewer: http://jsonviewer.stack.hu/

In [17]:
import pandas as pd
import requests

In [3]:
respons = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=4e4c212e92d8641e313cf538122fb21f&language=en-US&page=1')

In [18]:
df = pd.DataFrame(respons.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [19]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,26.8564,9.072,306
1,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,76.5853,8.916,1926
2,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,185.1949,8.725,30755
3,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,175.9168,8.704,3480
4,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,43.2937,8.687,23159
5,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,170.6013,8.670,6029
6,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,31.1864,8.572,14042
7,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,23.7258,8.569,17594
8,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,25.5182,8.565,10112
9,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,24.4676,8.551,726
10,1383731,Protector,Nikki's life is shattered when her daughter is...,2026-02-20,21.2717,8.540,426
11,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,42.5572,8.535,18528
12,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,44.1771,8.532,36086
13,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,13.4657,8.510,4600
14,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,30.2506,8.506,19424
15,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,8.4035,8.501,356
16,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,38.5236,8.501,26833
17,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,28.9950,8.491,20860
18,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-07-01,25.3528,8.482,12687
19,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,53.2750,8.481,40288

In [20]:
df = pd.DataFrame()

In [21]:
df

Empty DataFrame
Columns: []
Index: []

In [23]:
for i in range(1,429):
    respons = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=4e4c212e92d8641e313cf538122fb21f&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(respons.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [24]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,26.8564,9.072,306
1,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,76.5853,8.916,1926
2,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,185.1949,8.725,30755
3,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,175.9168,8.704,3480
4,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,43.2937,8.687,23159
...,...,...,...,...,...,...,...
8555,579,Jaws 2,Police chief Brody must protect the citizens o...,1978-06-16,5.9166,6.045,2139
8556,347984,6 Days,"London, England, April 1980. Six terrorists as...",2017-07-09,1.7274,6.000,769
8557,205588,Our Kind of Traitor,A young Oxford academic and his attorney girlf...,2016-05-05,1.6057,6.044,619
8558,109491,Beautiful Creatures,Ethan Wate just wants to get to know Lena Duch...,2013-02-13,4.9083,6.043,2949
8559,37770,Fantozzi to the Rescue,Fantozzi is now retired but continues to go to...,1990-12-21,0.8772,6.040,363

In [25]:
df.to_csv('movies.csv')