In [28]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [29]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1',headers = headers).text

In [30]:
soup = BeautifulSoup(webpage,'lxml')

In [24]:
# print(soup.prettify())

In [34]:
# soup.find_all('h1')[0].text

In [35]:
# len(soup.find_all('h2'))

In [38]:
#for i in soup.find_all('h2'):
    #print(i.text.strip())

In [39]:
# len(soup.find_all('div',class_ = 'rating_star_container'))

In [40]:
# for i in soup.find_all('div',class_ = 'rating_star_container'):
    # print(i.text.strip())

In [41]:
# len(soup.find_all('span',class_ = 'companyCardWrapper__companyRatingCount'))

In [42]:
# for i in soup.find_all('span',class_ = 'companyCardWrapper__companyRatingCount'):
#     print(i.text.strip())

In [31]:
company = soup.find_all('div',itemtype='http://schema.org/ListItem')

In [32]:
company

[<div class="companyCardWrapper" itemprop="itemListElement" itemscope="itemscope" itemtype="http://schema.org/ListItem"><meta content="1" itemprop="position"/> <meta content="TCS" itemprop="name"/> <meta content="Tata Consultancy Services" itemprop="alternateName"/> <meta content="https://www.ambitionbox.com/overview/tcs-overview" itemprop="url"/> <meta content="https://static.ambitionbox.com/alpha/company/photos/logos/tcs-d-6a2a531408440-d-6a2a5419543b5.jpg" itemprop="image"/> <div class="companyCardWrapper__primaryInformation"><div class="companyCardWrapper__companyLogo"><img alt="Tata Consultancy Services logo" height="50" loading="lazy" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/aHR0cHM6Ly9tZWRpYS5uYXVrcmkuY29tL21lZGlhL2FiY29tcGxvZ28vdGNzLW9yaWdpbmFsLmpwZw.webp" width="50"/></div> <div class="companyCardWrapper__metaInformation"><div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName"><h2 class="companyCardWrapper__companyName" title="TCS">
 									TCS
 								</h2></a> <!-- --></div> <button arialabel="Follow" class="companyCardWrapper__FollowCTA g-btn g-btn--text g-btn--md" data-testid="" title="Follow" type="button"><!-- --> <span class="g-btn__label g-btn__label--md g-btn__label--text g-btn__label--loader">Follow</span> <!-- --> <!-- --></button> <!-- --></div> <div class="companyCardWrapper__ratingWrapper"><div class="companyCardWrapper__companyRatingWrapper"><div class="companyCardWrapper__companyRating"><div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#FFBA01" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.3<!-- --></div></div></div></div> <span class="companyCardWrapper__companyRatingCount">
 								(1.2L)
 							</span></div> <span class="companyCardWrapper__interLinking">
 							IT Services &amp; Consulting | Bengaluru +449 other locations
 						</span> <!-- --> <div class="companyCardWrapper__ratingComparisonWrapper"><div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsup logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsUp.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--high">Highly Rated For</span></div> <span class="companyCardWrapper__ratingValues">Job Security</span></div> <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span></div></div></div> <div class="viewSalaryInsights"><div class="salaryInsightsText">To view salary insights</div> <div class="designationSelectionText">
 							Select designation
 						</div></div> <!-- --></div></div> <div class="companyCardWrapper__tertiaryInformation"><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/reviews/tcs-reviews" target="_blank"><span class="companyCardWrapper__ActionCount">1.2L</span> <span class="companyCardWrapper__ActionTitle">Reviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/salaries/tcs-salaries" target="_blank"><span class="companyCardWrapper__ActionCount">10.4L</span> <span class="companyCardWrapper__ActionTitle">Salaries</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/interviews/tcs-interview-questions" target="_blank"><span class="companyCardWrapper__ActionCount">11.4k</span> <span class="companyCardWrapper__ActionTitle">Interviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/jobs/tcs-jobs-cmp" target="_blank"><span class="companyCardWrapper__ActionCount">5.3k</span> <span class="companyCardWrapper__ActionTitle">Jobs</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/benefits/tcs-benefits" target="_blank"><span class="companyCardWrapper__ActionCount">11k</span> <span class="companyCardWrapper__ActionTitle">Benefits</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/photos/tcs-photos" target="_blank"><span class="companyCardWrapper__ActionCount">100</span> <span class="companyCardWrapper__ActionTitle">Photos</span></a></div></div>,
 <div class="companyCardWrapper" itemprop="itemListElement" itemscope="itemscope" itemtype="http://schema.org/ListItem"><meta content="2" itemprop="position"/> <meta content="Accenture" itemprop="name"/> <meta content="Accenture overview" itemprop="alternateName"/> <meta content="https://www.ambitionbox.com/overview/accenture-overview" itemprop="url"/> <meta content="https://static.ambitionbox.com/alpha/company/photos/logos/accenture.jpg" itemprop="image"/> <div class="companyCardWrapper__primaryInformation"><div class="companyCardWrapper__companyLogo"><img alt="Accenture logo" height="50" loading="lazy" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/aHR0cHM6Ly9tZWRpYS5uYXVrcmkuY29tL21lZGlhL2FiY29tcGxvZ28vYWNjZW50dXJlLW9yaWdpbmFsLmpwZw.webp" width="50"/></div> <div class="companyCardWrapper__metaInformation"><div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName companyCardWrapper__companyName--m8"><h2 class="companyCardWrapper__companyName" title="Accenture">
 									Accenture
 								</h2></a> <!-- --></div> <button arialabel="Follow" class="companyCardWrapper__FollowCTA g-btn g-btn--text g-btn--md" data-testid="" title="Follow" type="button"><!-- --> <span class="g-btn__label g-btn__label--md g-btn__label--text g-btn__label--loader">Follow</span> <!-- --> <!-- --></button> <!-- --></div> <div class="companyCardWrapper__ratingWrapper"><div class="companyCardWrapper__companyRatingWrapper"><div class="companyCardWrapper__companyRating"><div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#9acd32" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.7<!-- --></div></div></div></div> <span class="companyCardWrapper__companyRatingCount">
 								(75.4k)
 							</span></div> <span class="companyCardWrapper__interLinking">
 							IT Services &amp; Consulting | Bengaluru +261 other locations
 						</span> <!-- --> <div class="companyCardWrapper__ratingComparisonWrapper"><!-- --> <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span></div></div></div> <div class="viewSalaryInsights"><div class="salaryInsightsText">To view salary insights</div> <div class="designationSelectionText">
 							Select designation
 						</div></div> <!-- --></div></div> <div class="companyCardWrapper__tertiaryInformation"><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/reviews/accenture-reviews" target="_blank"><span class="companyCardWrapper__ActionCount">75.4k</span> <span class="companyCardWrapper__ActionTitle">Reviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/salaries/accenture-salaries" target="_blank"><span class="companyCardWrapper__ActionCount">7.1L</span> <span class="companyCardWrapper__ActionTitle">Salaries</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/interviews/accenture-interview-questions" target="_blank"><span class="companyCardWrapper__ActionCount">9.5k</span> <span class="companyCardWrapper__ActionTitle">Interviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/jobs/accenture-jobs-cmp" target="_blank"><span class="companyCardWrapper__ActionCount">20.7k</span> <span class="companyCardWrapper__ActionTitle">Jobs</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/benefits/accenture-benefits" target="_blank"><span class="companyCardWrapper__ActionCount">7k</span> <span class="companyCardWrapper__ActionTitle">Benefits</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/photos/accenture-photos" target="_blank"><span class="companyCardWrapper__ActionCount">49</span> <span class="companyCardWrapper__ActionTitle">Photos</span></a></div></div>,
 <div class="companyCardWrapper" itemprop="itemListElement" itemscope="itemscope" itemtype="http://schema.org/ListItem"><meta content="3" itemprop="position"/> <meta content="Wipro" itemprop="name"/> <meta content="Wipro overview" itemprop="alternateName"/> <meta content="https://www.ambitionbox.com/overview/wipro-overview" itemprop="url"/> <meta content="https://static.ambitionbox.com/alpha/company/photos/logos/wipro.jpg" itemprop="image"/> <div class="companyCardWrapper__primaryInformation"><div class="companyCardWrapper__companyLogo"><img alt="Wipro logo" height="50" loading="lazy" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/aHR0cHM6Ly9tZWRpYS5uYXVrcmkuY29tL21lZGlhL2FiY29tcGxvZ28vd2lwcm8tb3JpZ2luYWwuanBn.webp" width="50"/></div> <div class="companyCardWrapper__metaInformation"><div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName"><h2 class="companyCardWrapper__companyName" title="Wipro">
 									Wipro
 								</h2></a> <!-- --></div> <button arialabel="Follow" class="companyCardWrapper__FollowCTA g-btn g-btn--text g-btn--md" data-testid="" title="Follow" type="button"><!-- --> <span class="g-btn__label g-btn__label--md g-btn__label--text g-btn__label--loader">Follow</span> <!-- --> <!-- --></button> <!-- --></div> <div class="companyCardWrapper__ratingWrapper"><div class="companyCardWrapper__companyRatingWrapper"><div class="companyCardWrapper__companyRating"><div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#9acd32" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.6<!-- --></div></div></div></div> <span class="companyCardWrapper__companyRatingCount">
 								(66.5k)
 							</span></div> <span class="companyCardWrapper__interLinking">
 							IT Services &amp; Consulting | Hyderabad +375 other locations
 						</span> <!-- --> <div class="companyCardWrapper__ratingComparisonWrapper"><!-- --> <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span></div></div></div> <div class="viewSalaryInsights"><div class="salaryInsightsText">To view salary insights</div> <div class="designationSelectionText">
 							Select designation
 						</div></div> <!-- --></div></div> <div class="companyCardWrapper__tertiaryInformation"><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/reviews/wipro-reviews" target="_blank"><span class="companyCardWrapper__ActionCount">66.5k</span> <span class="companyCardWrapper__ActionTitle">Reviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/salaries/wipro-salaries" target="_blank"><span class="companyCardWrapper__ActionCount">4.9L</span> <span class="companyCardWrapper__ActionTitle">Salaries</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/interviews/wipro-interview-questions" target="_blank"><span class="companyCardWrapper__ActionCount">7k</span> <span class="companyCardWrapper__ActionTitle">Interviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/jobs/wipro-jobs-cmp" target="_blank"><span class="companyCardWrapper__ActionCount">4.1k</span> <span class="companyCardWrapper__ActionTitle">Jobs</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/benefits/wipro-benefits" target="_blank"><span class="companyCardWrapper__ActionCount">4.9k</span> <span class="companyCardWrapper__ActionTitle">Benefits</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/photos/wipro-photos" target="_blank"><span class="companyCardWrapper__ActionCount">121</span> <span class="companyCardWrapper__ActionTitle">Photos</span></a></div></div>,
 <div class="companyCardWrapper" itemprop="itemListElement" itemscope="itemscope" itemtype="http://schema.org/ListItem"><meta content="4" itemprop="position"/> <meta content="Cognizant" itemprop="name"/> <meta content="Cognizant overview" itemprop="alternateName"/> <meta content="https://www.ambitionbox.com/overview/cognizant-overview" itemprop="url"/> <meta content="https://static.ambitionbox.com/alpha/company/photos/logos/cognizant-d.jpg" itemprop="image"/> <div class="companyCardWrapper__primaryInformation"><div class="companyCardWrapper__companyLogo"><img alt="Cognizant logo" height="50" loading="lazy" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/aHR0cHM6Ly9tZWRpYS5uYXVrcmkuY29tL21lZGlhL2FiY29tcGxvZ28vY29nbml6YW50LW9yaWdpbmFsLmpwZw.webp" width="50"/></div> <div class="companyCardWrapper__metaInformation"><div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName"><h2 class="companyCardWrapper__companyName" title="Cognizant">
 									Cognizant
 								</h2></a> <!-- --></div> <button arialabel="Follow" class="companyCardWrapper__FollowCTA g-btn g-btn--text g-btn--md" data-testid="" title="Follow" type="button"><!-- --> <span class="g-btn__label g-btn__label--md g-btn__label--text g-btn__label--loader">Follow</span> <!-- --> <!-- --></button> <!-- --></div> <div class="companyCardWrapper__ratingWrapper"><div class="companyCardWrapper__companyRatingWrapper"><div class="companyCardWrapper__companyRating"><div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#9acd32" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.7<!-- --></div></div></div></div> <span class="companyCardWrapper__companyRatingCount">
 								(62.8k)
 							</span></div> <span class="companyCardWrapper__interLinking">
 							IT Services &amp; Consulting | Hyderabad +234 other locations
 						</span> <!-- --> <div class="companyCardWrapper__ratingComparisonWrapper"><!-- --> <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span></div></div></div> <div class="viewSalaryInsights"><div class="salaryInsightsText">To view salary insights</div> <div class="designationSelectionText">
 							Select designation
 						</div></div> <!-- --></div></div> <div class="companyCardWrapper__tertiaryInformation"><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/reviews/cognizant-reviews" target="_blank"><span class="companyCardWrapper__ActionCount">62.8k</span> <span class="companyCardWrapper__ActionTitle">Reviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/salaries/cognizant-salaries" target="_blank"><span class="companyCardWrapper__ActionCount">6.1L</span> <span class="companyCardWrapper__ActionTitle">Salaries</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/interviews/cognizant-interview-questions" target="_blank"><span class="companyCardWrapper__ActionCount">6.6k</span> <span class="companyCardWrapper__ActionTitle">Interviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/jobs/cognizant-jobs-cmp" target="_blank"><span class="companyCardWrapper__ActionCount">953</span> <span class="companyCardWrapper__ActionTitle">Jobs</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/benefits/cognizant-benefits" target="_blank"><span class="companyCardWrapper__ActionCount">5.7k</span> <span class="companyCardWrapper__ActionTitle">Benefits</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/photos/cognizant-photos" target="_blank"><span class="companyCardWrapper__ActionCount">102</span> <span class="companyCardWrapper__ActionTitle">Photos</span></a></div></div>,
 <div class="companyCardWrapper" itemprop="itemListElement" itemscope="itemscope" itemtype="http://schema.org/ListItem"><meta content="5" itemprop="position"/> <meta content="Capgemini" itemprop="name"/> <meta content="Capgemini overview" itemprop="alternateName"/> <meta content="https://www.ambitionbox.com/overview/capgemini-overview" itemprop="url"/> <meta content="https://static.ambitionbox.com/alpha/company/photos/logos/capgemini-d.jpg" itemprop="image"/> <div class="companyCardWrapper__primaryInformation"><div class="companyCardWrapper__companyLogo"><img alt="Capgemini logo" height="50" loading="lazy" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/aHR0cHM6Ly9tZWRpYS5uYXVrcmkuY29tL21lZGlhL2FiY29tcGxvZ28vY2FwZ2VtaW5pLW9yaWdpbmFsLmpwZw.webp" width="50"/></div> <div class="companyCardWrapper__metaInformation"><div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName"><h2 class="companyCardWrapper__companyName" title="Capgemini">
 									Capgemini

In [33]:
len(company)

20

In [34]:
name = []
rating = []
review_count = []
about = []
for i in company:
    name.append(i.find('h2',class_='companyCardWrapper__companyName').text.strip())
    rating.append(i.find('div',class_ = 'rating_star_container').text.strip())
    review_count.append(i.find('span',class_ = 'companyCardWrapper__companyRatingCount').text.strip())
    about.append(i.find('span',class_ = 'companyCardWrapper__interLinking').text.strip())

In [35]:
company[0].find_all('div',class_='companyCardWrapper__tertiaryInformation')[0]

<div class="companyCardWrapper__tertiaryInformation"><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/reviews/tcs-reviews" target="_blank"><span class="companyCardWrapper__ActionCount">1.2L</span> <span class="companyCardWrapper__ActionTitle">Reviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/salaries/tcs-salaries" target="_blank"><span class="companyCardWrapper__ActionCount">10.4L</span> <span class="companyCardWrapper__ActionTitle">Salaries</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/interviews/tcs-interview-questions" target="_blank"><span class="companyCardWrapper__ActionCount">11.4k</span> <span class="companyCardWrapper__ActionTitle">Interviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/jobs/tcs-jobs-cmp" target="_blank"><span class="companyCardWrapper__ActionCount">5.3k</span> <span class="companyCardWrapper__ActionTitle">Jobs</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/benefits/tcs-benefits" target="_blank"><span class="companyCardWrapper__ActionCount">11k</span> <span class="companyCardWrapper__ActionTitle">Benefits</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/photos/tcs-photos" target="_blank"><span class="companyCardWrapper__ActionCount">100</span> <span class="companyCardWrapper__ActionTitle">Photos</span></a></div>

In [36]:
name = []
rating = []
review_count = []
about = []
salaries = []
interviews = []
benefits = []

for i in company:
    name.append(i.find('h2', class_='companyCardWrapper__companyName').text.strip())
    rating.append(i.find('div', class_='rating_star_container').text.strip())
    review_count.append(i.find('span', class_='companyCardWrapper__companyRatingCount').text.strip())
    about.append(i.find('span', class_='companyCardWrapper__interLinking').text.strip().split('|')[0].strip())

    # tertiary info block (salaries, interviews, benefits, etc.)
    tertiary_info = i.find('div', class_='companyCardWrapper__tertiaryInformation')
    
    data = {}
    if tertiary_info:
        actions = tertiary_info.find_all('a', class_='companyCardWrapper__ActionWrapper')
        for action in actions:
            count = action.find('span', class_='companyCardWrapper__ActionCount')
            title = action.find('span', class_='companyCardWrapper__ActionTitle')
            if count and title:
                data[title.get_text(strip=True)] = count.get_text(strip=True)

    salaries.append(data.get('Salaries'))
    interviews.append(data.get('Interviews'))
    benefits.append(data.get('Benefits'))

In [37]:
data = {'company_name':name,"sector ":about,"Rating":rating,"reviews":review_count,"Average salary":salaries,"Number of Interview":interviews,"Benifited":benefits}

In [38]:
df = pd.DataFrame(data)

In [39]:
df

,company_name,sector,Rating,reviews,Average salary,Number of Interview,Benifited
0,TCS,IT Services & Consulting,3.3,(1.2L),10.4L,11.4k,11k
1,Accenture,IT Services & Consulting,3.7,(75.4k),7.1L,9.5k,7k
2,Wipro,IT Services & Consulting,3.6,(66.5k),4.9L,7k,4.9k
3,Cognizant,IT Services & Consulting,3.7,(62.8k),6.1L,6.6k,5.7k
4,Capgemini,IT Services & Consulting,3.6,(54.9k),5L,5.6k,3.9k
5,HDFC Bank,Banking,3.8,(54k),1.5L,3.2k,3.5k
6,Infosys,IT Services & Consulting,3.5,(50k),5.3L,8.5k,5k
7,HCLTech,IT Services & Consulting,3.4,(47.1k),3.9L,4.6k,4k
8,ICICI Bank,Banking,3.9,(46.8k),1.6L,3k,3.9k
9,Tech Mahindra,IT Services & Consulting,3.3,(44.3k),2.9L,4.7k,3.5k
10,Genpact,Analytics & KPO,3.6,(43.5k),2.4L,4k,3.7k
11,TP,BPO,3.9,(39.8k),1L,2.3k,2k
12,Axis Bank,Banking,3.6,(34.2k),1L,2k,2.3k
13,Jio,Telecom,4.4,(34.1k),61.4k,4.5k,2.7k
14,Concentrix Corporation,BPO,3.5,(33k),1.3L,2k,3.2k
15,Amazon,Internet,3.9,(32.5k),1.6L,6.1k,3.5k
16,Reliance Retail,Retail,3.9,(27.8k),74.7k,2k,1.9k
17,iEnergizer,BPO,4.6,(27.6k),25.1k,1.7k,750
18,LTM Limited,IT Services & Consulting,3.6,(27.2k),2L,3.5k,871
19,HDB Financial Services,NBFC,3.9,(26.3k),49.8k,1.1k,1.6k

In [51]:
company_data = pd.DataFrame()

for j in range(1,100):
    url = 'https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page={}'.format(j)
    
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage = requests.get(url,headers = headers).text

    soup = BeautifulSoup(webpage,'lxml')
    company = soup.find_all('div',itemtype='http://schema.org/ListItem')
    name = []
    rating = []
    review_count = []
    about = []
    salaries = []
    interviews = []
    benefits = []
    
    for i in company:
        name.append(i.find('h2', class_='companyCardWrapper__companyName').text.strip())
        rating.append(i.find('div', class_='rating_star_container').text.strip())
        review_count.append(i.find('span', class_='companyCardWrapper__companyRatingCount').text.strip())
        about.append(i.find('span', class_='companyCardWrapper__interLinking').text.strip().split('|')[0].strip())
    
        # tertiary info block (salaries, interviews, benefits, etc.)
        tertiary_info = i.find('div', class_='companyCardWrapper__tertiaryInformation')
        
        data = {}
        if tertiary_info:
            actions = tertiary_info.find_all('a', class_='companyCardWrapper__ActionWrapper')
            for action in actions:
                count = action.find('span', class_='companyCardWrapper__ActionCount')
                title = action.find('span', class_='companyCardWrapper__ActionTitle')
                if count and title:
                    data[title.get_text(strip=True)] = count.get_text(strip=True)
    
        salaries.append(data.get('Salaries'))
        interviews.append(data.get('Interviews'))
        benefits.append(data.get('Benefits'))

        data = {'company_name':name,"sector ":about,"Rating":rating,"reviews":review_count,"Average salary":salaries,"Number of Interview":interviews,"Benifited":benefits}
        df = pd.DataFrame(data)

        company_data = pd.concat([company_data, df], ignore_index=True)

In [52]:
company_data

,company_name,sector,Rating,reviews,Average salary,Number of Interview,Benifited
0,TCS,IT Services & Consulting,3.3,(1.2L),10.4L,11.4k,11k
1,TCS,IT Services & Consulting,3.3,(1.2L),10.4L,11.4k,11k
2,Accenture,IT Services & Consulting,3.7,(75.4k),7.1L,9.5k,7k
3,TCS,IT Services & Consulting,3.3,(1.2L),10.4L,11.4k,11k
4,Accenture,IT Services & Consulting,3.7,(75.4k),7.1L,9.5k,7k
...,...,...,...,...,...,...,...
4615,Indian Railways,Railways,4.2,(2.2k),3.6k,116,167
4616,Lava International,Consumer Electronics & Appliances,3.9,(2.2k),4.4k,95,312
4617,Henry Harvin Education,EdTech,4.0,(2.2k),989,138,76
4618,Whirlpool,Consumer Electronics & Appliances,4.0,(2.2k),8k,122,209
4619,Shahi Exports,Fashion & Textile,3.9,(2.2k),6.9k,128,236

In [48]:
company_data.to_csv('company_data.csv', index=False)